sudo: false
language: objective-c
xcode_project: cameo.xcodeproj
xcode_scheme: cameo_test
xcode_sdk: iphonesimulator
osx_image: "xcode7.3"
env:
  - secure: d+gB0SQfz2FRzg/Gk7OmgQl+z+R9aTjpZCFWGydZsuQQdVQFIoQH/Kas7vGXBjIInuBIKqaCChQCe7PxB5qoSUsXKLReCpS5/gh8fjnYDVzWjVTg9bIOS4etYCsImCZAnqdC1GmwLtpiOioRdoc9KKaYkDulNdDpqGHKGWO21D8=
deploy:
  provider: script
  script: ./scripts/push.sh
  on:
    tags: true
    osx_image: "xcode7.3"
