sudo: false
language: objective-c
matrix:
  include:
    - osx_image: "xcode7.3"
    - osx_image: "xcode8"
    - osx_image: "xcode8.1"
xcode_project: cameo.xcodeproj
xcode_scheme: cameo_test
xcode_sdk: iphonesimulator
