sudo: false
language: objective-c
xcode_project: cameo.xcodeproj
xcode_scheme: cameo_test
xcode_sdk: iphonesimulator
osx_image: "xcode7.3"
env:
  - secure: lQSVvXFPeI3MessmO++QeFsheoApH5UwjF02bWOhPEQLdlw7POMn/UV3AptpSfyGeiDZzf+xSjg3JU6jRNR+qh2HzNYBBmM2B9mOvxM3rVjw7lwU3bUBAPsVEpfM4U2S+VPpTFQ4pdtE7TqJuzfbKGej6Jcdk7BSHscNwCD+x60=
deploy:
  provider: script
  script: ./scripts/push.sh
  on:
    tags: true
    osx_image: "xcode7.3"
