name: Build Workflow
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: macOS-latest
    strategy:
      matrix:
        run-config:
          - { scheme: 'MPCF-Reflector-ios', destination: 'platform=iOS Simulator,OS=13.4.1,name=iPhone 8' }
          - { scheme: 'MPCF-TestRunner-ios', destination: 'platform=iOS Simulator,OS=13.4.1,name=iPhone 8' }
    steps:
      - uses: actions/checkout@v1
      - name: Setup homebrew packages
        run: brew bundle
      - name: Show information
        run: |
          xcode-select -p
          xcodebuild -workspace MPCF-TestBench.xcworkspace -scheme '${{ matrix.run-config['scheme'] }}' -showBuildSettings
          xcodebuild -workspace MPCF-TestBench.xcworkspace -scheme '${{ matrix.run-config['scheme'] }}' -showsdks
          xcodebuild -workspace MPCF-TestBench.xcworkspace -scheme '${{ matrix.run-config['scheme'] }}' -showdestinations
      - name: Build packages
        run: |
          xcodebuild clean test -scheme cameo_test -destination "platform=iOS Simulator,OS=13.4.1,name=iPhone 8" 
