name: Deploy Workflow
on:
  push:
    tags:
      - "*"
jobs:
  build:
    name: Build
    runs-on: macOS-latest
    strategy:
      matrix:
        run-config:
          - { scheme: "cameo_test", destination: "platform=iOS Simulator,name=iPhone 8" }
          - { scheme: "cameo_test", destination: "platform=iOS Simulator,name=iPhone 12" }
          - { scheme: "cameo_test", destination: "platform=iOS Simulator,name=iPhone 13" }
          - { scheme: "cameo_test", destination: "platform=iOS Simulator,name=iPad Pro (9.7-inch)" }
    steps:
      - uses: actions/checkout@v1
      - name: Install CocoaPods
        run: pod install
      - name: Show information
        run: |
          xcode-select -p
          xcodebuild -workspace cameo.xcworkspace -scheme "${{ matrix.run-config['scheme'] }}" -showBuildSettings
          xcodebuild -workspace cameo.xcworkspace -scheme "${{ matrix.run-config['scheme'] }}" -showsdks
          xcodebuild -workspace cameo.xcworkspace -scheme "${{ matrix.run-config['scheme'] }}" -showdestinations
      - name: Test packages
        run: xcodebuild clean test -workspace cameo.xcworkspace -scheme "${{ matrix.run-config['scheme'] }}" -destination "${{ matrix.run-config['destination'] }}" -showBuildTimingSummary
      - name: Deploy to CocoaPods
        run: ./scripts/push.sh
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
